### ISSUE TITLE
Rename headers to response_headers

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily-apache#3]
The bridge currently provides apache's response headers under `server.headers`. I'd like to see it provide it under `server.response_headers` instead. Doing so would allow the bridge to provide request headers under that name.

**Comment by Acconut** [comment]
Could it be that you mistook request with response? `server.headers` currently provides the request header (aka incoming headers) and should rather by named `server.request_headers`, or did I misunderstand you?

**Comment by FascinatedBox** [comment]
Yeah I mixed up the words. You're right. >.>

**Comment by Acconut** [comment]
I submitted a patch in #5 for this :)
