### ISSUE TITLE
Proposal for response_set/unset

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily-apache#4]
The bridge should provide some means of changing the response headers. This is a proposal to add two functions to the `server` namespace:

`define response_set(key: String, value: String)`

This function will either update an existing header or create a new one. If Apache has already sent any content, then this function should raise `RuntimeError` explaining that. If either `key` or `value` is empty, then `ValueError` should be raised.

`define response_unset(key: String)`

This function should unset an existing header. Again, if headers have already been sent, then this should raise `RuntimeError`. If the header in question doesn't exist, then this should be a no-op.

**Comment by Acconut** [comment]
Another possible approach would be to have a `response_headers: Hash[String, String]` variable similar to `request_headers` which can be filled with values as wanted. Once you are finished with setting headers, you call `write_header(status_code: Integer)` to send the response headers and status code.

What do you think?

**Comment by FascinatedBox** [comment]
Hmm...I like that the header set/unset functions can be grepped. So it's clear what someone's getting themselves into. Also, from an internal perspective, dynaload would be tough. There'd need to be runtime lookup of the response headers from write_header. Further, request_headers may have not even been referenced.

**Comment by Acconut** [comment]
> Also, from an internal perspective, dynaload would be tough. There'd need to be runtime lookup of the response headers from write_header.

That's right. A bit unrelated question: Are there plans to make parts of the stdlib or lily-apache written in Lily instead of C? For example, the Tainted and HtmlString types could be implemented fully in Lily, IIRC.

**Comment by FascinatedBox** [comment]
Right now I haven't thought much outside of making the core work, so no planning has been in that direction just yet. But I wouldn't mind some parts of Lily's standard library (like json, for example) to be written in the language itself. That makes it easier for people to update it, and there's less lines getting that to work versus making it in C. But for the essentials, like networking, it might have to be a C wrapper because of the plumbing that needs to be reached.

My only hard no is that I don't want dynaload to bootstrap code. To give an example, Tainted's constructor used to be a dynaload entry that was to the effect of:

`Tainted\0class Tainted[A](var @value: A) { }`

I've moved away from dynaload doing that, so that dynaload can't do anything spooky.

Perhaps some set of Lily functions can be provided by having a module that wraps over what is inside of `server` to add extra functionality.

**Comment by Acconut** [comment]
Thank you for the details, I am looking forward to seeing how this situation will evolve in the future :) I also apologize for my inactivity, I will try to PR for this issue up and running.

> Perhaps some set of Lily functions can be provided by having a module that wraps over what is inside of server to add extra functionality.

Yes, this is indeed a possible approach but not the most intuitive and efficient one.

**Comment by FascinatedBox** [comment]
I agree: It's not a great solution. Perhaps a better one will come along in time.

As for the inactivity, NBD there.

**Comment by Acconut** [comment]
Can be closed in favour of #6.

**Comment by FascinatedBox** [comment]
Closing this as part of the migration to gitlab: https://gitlab.com/FascinatedBox/lily-apache/issues/4
